language: go
sudo: false

go:
  - 1.10.3

before_install:
  - go get -u golang.org/x/vgo

script:
  - vgo test -race -coverprofile=profile.out -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
